regression_tutorial; 
plot_example_classification_1d;
preference_learning_GP; 
kernels_examples; 
plot_kernel_approximation; 
BO_figure_thesis; 
BO_figure_thesis_hyperparametrs;

plot_GP_sampling; 

BBO_figure_thesis; 
PBO_figure_thesis;
report_solution_to_noisy_BO;
figure_active_sampling;
figure_sampling_preference; 
plot_GP_sampling_SSGP_vs_RRGP;
plot_GP_sampling_decoupled_bases_vs_normal;
plot_GP_sampling_binary;
duels_analysis;
plot_duels_analysis;
duels_analysis_ranking;
duels_analysis_conditional_vs_normal;