regression_tutorial;
regression_tutorial_hyperparameters;
plot_example_classification_1d;

preference_learning_GP;
kernels_examples;
plot_kernel_approximation;
BO_principle

BO_hyperparameters_effect
plot_GP_sampling;

PBO_figure_thesis;
report_solution_to_noisy_BO;
figure_active_sampling;
plot_GP_sampling_SSGP_vs_RRGP;
plot_GP_sampling_decoupled_bases_vs_normal;
plot_GP_sampling_binary;

% plot_duels_analysis;
duels_analysis_ranking;
 PBO_pareto_front;
BBO_pareto_front;

BatchMUC_behavior
 
figure_MUC;
Copeland_vs_PKG
figure_sampling_preference;

preference_learning_GP_comparison_wo_conditionning

performance_GP_sampling
BBO_proba_vs_latent
uncertainty

 
%%
plot_cBKG
plot_cBKG_evolution
plot_cBKG_linARD.m
